[package]
name = "obsidianprotocol"
version = "0.1.0"
description = "Universal credit infrastructure for all intelligence types"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "obsidianprotocol"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
# These features are used internally by Anchor macros
custom-heap = []
custom-panic = []
anchor-debug = []


[dependencies]
anchor-lang = "0.31.1"

